def help_use():
    print("功能说明：")
    print("-w 对域名whois查询")
    print("-z 进行子域名查询")
    print("-wf WAF识别模块，调用wafw00f项目")
    print("-c 判断是否使用CND")
    print("-a 调用AWVS扫描")
    print("-s 调用sqlmap api")
    print("-up 对指定ip密码爆破")
    print("-cms CMS识别")
    print("-f 目录路径爆破")
    print("-nm nmap端口开放扫描")
    print("-zym 子域名扫描")
    print("-in 内网账号密码爆破")
    print("-or 对单个域名进行whois、子域名、waf识别、cnd、路径爆破、nmap端口开放查询、子域名识别")
    print("前面加-r 表示使用批量IP扫描，使用ip为dictionary/ip.txt")
    print("-own 对单个ip进行cms、whois、cnd、目录爆破、端口扫描、子域名扫描")
    print("-r -own 对多个ip进行cms、whois、cnd、目录爆破、端口扫描、子域名扫描")

